# PUSH REQUEST: SETP 2

name : test2

on:
  push:
    branches:
      - main

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: main
    steps:
    - run: echo "main"
  my_second_job:
    runs-on: ubuntu-latest
    name: dev-1
    steps:
    - run: echo "dev-1"