# PUSH REQUEST: SETP 1

name : test1

on:
  push:
    branches:
      - main

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: main
    steps:
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
